# Generated by Django 3.2.12 on 2022-07-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sports', 'Sports'), ('computer science', 'Computer Science'), ('Physics', 'Physics'), ('space', 'Space'), ('cinema', 'Cinema'), ('music', 'Music'), ('economy', 'Economy')], max_length=50, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('get_email', models.BooleanField(default=False, verbose_name='Get notified with top posts')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_categories', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
